# Linear Algebra - Group 3

1. Bryan Putra
2. Davin Pratama 
3. Matthew Emmeric

# Gaussian Elimination

Gaussian elimination, also known as row reduction, is an algorithm in linear algebra for solving a system of linear equations. It is usually understood as a sequence of operations performed on the corresponding matrix of coefficients.

The Gaussian Elimination has 2 mains steps which are the Forward Elimination and Back Substitution

For example we have 4 linear equations or we can call it linear system of equations:

\begin{align*}
3x-2y+5z    = 2\\        
4x+5y+8z+s  = 4\\        
x + y+2z+s  = 5\\         
2x+7y+6z+5s = 7
\end{align*}

    
In matrix notation, a linear system is where $$ Ax = b $$ 
where:  x are unknown vectors

$$\begin{bmatrix} 3 & -2 & 5 & 0 \\ 4 & 5 & 8 & 1 \\ 1 & 1 & 2 & 1 \\ 2 & 7 & 6 & 5 \end{bmatrix} \begin{bmatrix} x0 \\ x1 \\ x2 \\ x3 \end{bmatrix} = \begin{bmatrix} 2 \\ 4 \\ 5 \\ 7 \end{bmatrix}$$
    
To solve this, we will have to do the 2 main steps.

First is the Forward Elimination.
The Main idea of this step is to make everything below the diagonal line of the matrix we have above into zero.
We can picture the output being like this:  
       
$$\begin{bmatrix} 3 & -2 & 5 & 0 \\ 0 & -5.75 & -1 & -0.75 \\ 0 & 0 & 0.15 & 1 \\ 0 & 0 & 0 & 2.21785714 \end{bmatrix}$$
      
The output above is our first step to solve the linear system.

To actually do that first we focus on the matrix we have

$$\begin{bmatrix} 3 & -2 & 5 & 0 \\ 4 & 5 & 8 & 1 \\ 1 & 1 & 2 & 1 \\ 2 & 7 & 6 & 5 \end{bmatrix}$$

The first row of the matrix is already fixed and doesn't need any changing since we only need to turn numbers under the diagonal line of the matrix to 0. 
First we focus on the first column, we need to turn the 4 1 2 into zeros. To do that, we can loop through and multiply each row by factors which are (3 / 4, 3 / 1, 3 / 2) then we substract all of the multiplied numbers by 3 which is the number on the fixed row.

To make it more clear, it's basically like this:

4 is multiplied by 3 / 4 = 3  
1 is multiplied by 3 / 1 = 3  
2 is multiplied by 3 / 2 = 3

Dont forget that the other elements in the same row as 4 are also multiplied. Same goes for the substraction

As we can see all of them turned into the number 3 which is the first element on the fixed row
So then we substract all of those multiplied numbers by 3 and all of them will become 0

First Substraction : 
        
$$\begin{bmatrix} 3 & -2 & 5 & 0 \\ 3 & 3.75 & 6 & 0.75 \\ 3 & 3 & 6 & 3 \\ 3 & 10.5 & 9 & 7.5 \end{bmatrix} \begin{bmatrix} 2 \\ 3 \\ 15 \\ 10.5 \end{bmatrix} -> \begin{bmatrix} 3 & -2 & 5 & 0 \\ 0 & -5.75 & -1 & -0.75 \\ 0 & -5 & -1 & -3 \\ 0 & -12.5 & -4 & -7.5 \end{bmatrix} \begin{bmatrix} 2 \\ -1 \\ -13 \\ -8.5 \end{bmatrix}$$

Now the second row is the fixed row because it doesn't need any more changing. Now we focus on the elements below the second element in the fixed row which is -5.75. We want to make the elements below it zero just like what we did on the first step. Basically what we want to do is actually the exact same thing as before. So if it will be like this : 

Second Substraction :
        
$$\begin{bmatrix} 3 & -2 & 5 & 0 \\ 0 & -5.75 & -1 & -0.75 \\ 0 & -5.75 & -1.15 & -3.45 \\ 0 & -5.75 & -1.84 & -3.45 \end{bmatrix} \begin{bmatrix} 2 \\ -1 \\ -14.95 \\ -3.91 \end{bmatrix} -> \begin{bmatrix} 3 & -2 & 5 & 0 \\ 0 & -5.75 & -1 & -0.75 \\ 0 & 0 & 0.15 & -2.7 \\ 0 & 0 & 0.15 & 0.482143 \end{bmatrix} \begin{bmatrix} 2 \\ -1 \\ -13.95 \\ 0.519643 \end{bmatrix}$$
        
Then the next row becomes the fixed row and if we do the step again it will be like this :
      
$$\begin{bmatrix} 3 & -2 & 5 & 0 \\ 0 & -5.75 & -1 & -0.75 \\ 0 & 0 & 0.15 & 2.7 \\ 0 & 0 & 0 & 2.21785714 \end{bmatrix} \begin{bmatrix} x0 \\ x1 \\ x2 \\ x3 \end{bmatrix} = \begin{bmatrix} 2 \\ -1 \\ 13.95 \\ 13.43057 \end{bmatrix}$$

After we get the elements under the diagonal line to zero, we can start the next main step which is the Back Substitution.
    
$$ x[3] = \frac{b[3]}{a[3,3]} = \frac {13.430357}{2.217857} = 6.055556 $$

$$ x[2] = \frac{b[2] - a[2,3]×x[3]}{a[2,2]} = \frac{13.95 - 2.7 × 6.055556}{0.15} = -16 $$
    
$$ x[1] = \frac{b[1] - a[1,3]×x[3] - a[1,2]× x[2]}{a[1,1]} = \frac{(-1-(-0.75) x 6.055556-(-1) x (-16)}{-5.75} = 2.166667 $$

$$ x[0] = \frac{b[0] - a[0,3]×x[3] - a[0,2]× x[2] - a[0,1]× x[1]}{a[0,0]} = \frac{(2-0 × 6.055556-5 × (-16)-(-2) × 2.166667)}{3} = 28.777778 $$

So the Final Solution is : 

$$x[0] = 28.777778$$
$$x[1] = 2.166667$$
$$x[2] = -16$$
$$x[3] = 6.055556$$

In [ ]:
import numpy.linalg as la
import numpy as np


def gaussianElimination(coefficientsMatrix, constantVectors):
    if coefficientsMatrix.shape[1] != constantVectors.shape[0]: # if one of the matrix given's column is not equal
        print("Both Matrixes must have equal number of columns")
    else:
        # Forward Elimination
        print("First Matrix : \n" + str(coefficientsMatrix) + "\n")
        print(str(constantVectors) + "\n")

        n = len(constantVectors)
        x = np.zeros(n, float)

        for k in range(n - 1):
            for i in range(k + 1, n):
                if coefficientsMatrix[i, k] == 0: # if the number that we are looping through under the diagonal 
                                                  # line is already 0 then we skip it to check the next element             
                    continue
                factor = coefficientsMatrix[k, k] / coefficientsMatrix[i, k]
                for j in range(k, n):
                    coefficientsMatrix[i, j] = coefficientsMatrix[k, j] - coefficientsMatrix[i, j] * factor
                    # all the row elements under the fixed row will be multiplied by the factor
                    # then the row elements will be substracted by the elements within the fixed row
                constantVectors[i] = constantVectors[k] - constantVectors[i] * factor
                # do the same for the vectors without for loop because it only has 1 row/column (depends on how we 
                # visualize it)
                
        print("Updated Matrix : \n"+ str(coefficientsMatrix) + "\n" + str(constantVectors))

        # Back Substitution
        
        x[n-1] = constantVectors[n-1] / coefficientsMatrix[n-1, n-1]
        for i in range(n-2, -1, -1):
            sum_ax = 0
            for j in range(i + 1, n):
                sum_ax += coefficientsMatrix[i,j] * x[j]
            x[i] = (constantVectors[i] - sum_ax) / coefficientsMatrix[i,i]
        print("Solution :\n" + str(x))



# a = np.array([[3, -2, 5, 0],      <---- use this as first example
#               [4, 5, 8, 1],
#               [1, 1, 2, 1],
#               [2, 7, 6, 5]], float)
# b = np.array([2, 4, 5, 7], float)
# easyway = la.solve(a, b)
# print(easyway) 
# gaussianElimination(a, b)

# with numpy.linalg we can just use the .solve(coefficientsMatrix, constantVectors) if you want to do it the easier way

def getInputCoefMatrix():
    print("Please input a matrix from a valid equation")
    print("Input Coefficient Matrix")
    while True:
        row = int(input("Enter number of matrix rank [2-5] (like 3x3 or 4x4, etc): "))
        if(row < 2 or row > 5):
            continue
        else:
            print("Enter the elements in a single line (separated by space)")
            print("For Example (4x4) 3 -2 5 0 4 5 8 1 1 1 2 1 2 7 6 5 becomes \n[3,-2,5,0]\n[4,5,8,1]\n[1,1,2,1]\n[2,7,6,5]")
            elements = list(map(int, input().split()))
            matrix = np.array(elements, float).reshape(row, row)
            return matrix

def getInputConstantVectors(CoefMatrix):
    print("Constant Vectors")
    row = 1
    while True:
        column = int(input("Enter number of columns (Same amount as the Coefficient Matrix's matrix rank) : "))
        if(column != len(CoefMatrix[0])):
            continue
        else:
            while True:
                print("Enter the elements in a single line (separated by space)")
                elements = list(map(int, input().split()))
                if(len(elements) != column):
                    print("Please enter the valid amount of elements")
                    continue
                else:
                    matrix = np.array(elements, float)
                    return matrix
                    break
            break
                
o = getInputCoefMatrix()
o1 = getInputConstantVectors(o)

gaussianElimination(o, o1)


Please input a matrix from a valid equation
Input Coefficient Matrix


## LU Decomposition

In numerical analysis and linear algebra, LU Decomposition factors a matrix as the product of a lower triangular matrix and an upper triangular matrix.
Let A be a square matrix. An LU factorization refers to the factorization of A, with proper row and/or column orderings or permutations, into two factors, a lower triangular matrix L and an upper triangular matrix U, A=LU.

For example,

$$A = \begin{bmatrix} A11 & A12 & A13 \\ A21 & A22 & A23 \\ A31 & A32 & A33 \end{bmatrix}$$

$$L = \begin{bmatrix} 1 & 0 & 0 \\ L21 & 1 & 0 \\ L31 & L32 & 1 \end{bmatrix}$$

$$U = \begin{bmatrix} U11 & U12 & U13 \\ 0 & U22 & U23 \\ 0 & 0 & U33 \end{bmatrix}$$

        
Let A,
        
$$A = \begin{bmatrix} 1 & 2 & 4 \\ 3 & 8 & 14 \\ 2 & 6 & 13 \end{bmatrix}$$
        
Multiplying out LU and setting the answer equal to A gives
    
$$\begin{bmatrix} U11 & U12 & U13 \\ L21×U11 & L21×U12 & L21×U13 + U23 \\ L31×U11 & L31×U12 & L31×U13 + L32×U23 + U33 \end{bmatrix} = \begin{bmatrix} 1 & 2 & 4 \\ 3 & 8 & 14 \\ 2 & 6 & 13 \end{bmatrix}$$
    
From this equation, we can know that [U11 = 1], [U12 = 2], [U13 = 4].

Now consider the second row.

$$L21xU11 = 3; L21x1 = 3; L21 = 3$$

$$L21xU12 + U22 = 8; 3x2 + U22 = 8; U22 = 2$$

$$L21xU13 + U23 = 14; 3x4 + U23 = 14; U23 = 2$$


Now, solve the last row.

$$L31xU11 = 2; L31x1 = 2; L31 = 2$$

$$L31xU12 + L32xU22 = 6; 2x2 + L32x2 = 6; L32 = 1$$

$$L31xU13 + L32xU23 + U33 = 13; 2x4 + 1x2 + U33 = 13; U33 = 3$$


So, the LU decomposition of A is
        
$$A = \begin{bmatrix} 1 & 2 & 4 \\ 3 & 8 & 14 \\ 2 & 6 & 13 \end{bmatrix} = \begin{bmatrix} 1 & 0 & 0 \\ 3 & 1 & 0 \\ 2 & 1 & 1 \end{bmatrix} \begin{bmatrix} 1 & 2 & 4 \\ 0 & 2 & 2 \\ 0 & 0 & 3 \end{bmatrix}$$

In [5]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Jun 14 14:49:29 2020

@author: davinpc
"""
import numpy as np

MAX = 100
  

def luDecomposition(mat): 
      
    n = len(mat[0])
    
    lower = [[0 for x in range(n)]  
                for y in range(n)]
    upper = [[0 for x in range(n)]  
                for y in range(n)]
                  
    # Decomposing matrix into Upper  
    # and Lower triangular matrix 
    for i in range(n): 
  
        # Upper Triangular 
        for k in range(i, n):  
  
            # Summation of L(i, j) * U(j, k) 
            sum = 0
            for j in range(i): 
                sum += (lower[i][j] * upper[j][k])
  
            # Evaluating U(i, k) 
            upper[i][k] = mat[i][k] - sum
  
        # Lower Triangular 
        for k in range(i, n): 
            if (i == k): 
                lower[i][i] = 1 # Diagonal as 1 
            else: 
  
                # Summation of L(k, j) * U(j, i) 
                sum = 0
                for j in range(i): 
                    sum += (lower[k][j] * upper[j][i])
  
                # Evaluating L(k, i) 
                lower[k][i] = int((mat[k][i] - sum) / upper[i][i])
  
    # for displaying nicely 
    print("Lower Triangular\t\tUpper Triangular")
  
    # Displaying the result : 
    for i in range(n): 
          
        # Lower 
        for j in range(n): 
            print(lower[i][j], end = "\t")
        print("", end = "\t")
  
        # Upper 
        for j in range(n): 
            print(upper[i][j], end = "\t")
        print("")
  
# Driver code 

# mat = [[2, -1, -2], 
#        [-4, 6, 3],  <<-- example
#        [-4, -2, 8]]

def getInputMatrix():
    print("Please input a matrix from a valid equation")
    print("Input Matrix")
    while True:
        row = int(input("Enter number of matrix rank [2-5] (like 3x3 or 4x4, etc): "))
        if(row < 2 or row > 5):
            continue
        else:
            while True:
                print("Enter the elements in a single line (separated by space)")
                print("For Example 3 -2 5 0 4 5 8 1 1 1 2 1 2 7 6 5 becomes \n[3,-2,5,0]\n[4,5,8,1]\n[1,1,2,1]\n[2,7,6,5]")
                elements = list(map(int, input().split()))
                if(row ** 2 != len(elements)):                  
                    print("Please enter the valid amount of elements")
                    continue
                else:
                    matrix = np.array(elements, float).reshape(row, row)
                    return matrix
                    break
            break

inputMatrix = getInputMatrix()

luDecomposition(inputMatrix)

Please input a matrix from a valid equation
Input Matrix
Enter number of matrix rank [2-5] (like 3x3 or 4x4, etc): 3
Enter the elements in a single line (separated by space)
For Example 3 -2 5 0 4 5 8 1 1 1 2 1 2 7 6 5 becomes 
[3,-2,5,0]
[4,5,8,1]
[1,1,2,1]
[2,7,6,5]
3 2 1 2 2 2 2 2 2 2
Please enter the valid amount of elements
Enter the elements in a single line (separated by space)
For Example 3 -2 5 0 4 5 8 1 1 1 2 1 2 7 6 5 becomes 
[3,-2,5,0]
[4,5,8,1]
[1,1,2,1]
[2,7,6,5]
3 2 1 3 2 1 3 2 1 3 2 1
Please enter the valid amount of elements
Enter the elements in a single line (separated by space)
For Example 3 -2 5 0 4 5 8 1 1 1 2 1 2 7 6 5 becomes 
[3,-2,5,0]
[4,5,8,1]
[1,1,2,1]
[2,7,6,5]
2 -1 -2 -4 6 3 -4 -2 8
Lower Triangular		Upper Triangular
1	0	0		2.0	-1.0	-2.0	
-2	1	0		0	4.0	-1.0	
-2	-1	1		0	0	3.0	


# Eigenvalue Decomposition

In linear algebra, eigendecomposition or sometimes spectral decomposition is the factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way.

**Properties of Eigendecomposition:**
1. The determinant of A is equal to the product of its eigenvalues.
2. The trace of A is equal to the sum of its eigenvalues.
3. The eigenvalues of the $A^{-1}$ are the $\lambda^{-1}_i$.
4. The eigenvalues of $A^n$ are $\lambda^n_i$.
5. In general, the eigenvalues of $f(A)$ are $f(λ_i)$.
6. The eigenvectors of $A^{−1}$ are the same as the eigenvectors of $A$.
7. If $A$ is hermitian (its conjugate transpose is equal to itself) and full-rank (all rows or columns are linearly independent), then the eigenvectors are mutually orthogonal (the dot-product between any two eigenvectors is zero) and the eigenvalues are real.
8. $A$ is invertible if all its eigenvalues are different from zero and vice-versa.
9. If the eigenvalues of matrix $A$ are distinct (not repeated), then $A$ can be eigendecomposed.

To demonstrate how this decomposition is done, let matrix A be the matrix being operated on.

$$A = \begin{bmatrix} 2 & -4 & 2 \\ -2 & 1 & 2 \\ 4 & 2 & 5 \end{bmatrix}$$

***Determining the eigenvectors and the eigenvalues of a given matrix.***

**Step 1: Expanding the determinant of the matrix.**

$$det\begin{pmatrix} -2-\lambda & -4 & 2 \\ -2 & 1-\lambda & 2 \\ 4 & 2 & 5-\lambda \end{pmatrix} = 0$$

$$(−2−\lambda)[(1−\lambda)(5−\lambda)−2×2]+4[(−2)×(5−\lambda)−4×2]+2[(−2)×2−4(1−\lambda)]=0$$

<br></br>
**Step 2: Expanding the brackets and simplifying.**

$$−\lambda^3+4\lambda^2+27\lambda−90=0$$
$$\lambda^3-4\lambda^2-27\lambda+90=0$$

<br></br>
**Step 3: Identifying the eigenvalues.**

$$3^3−4×3^2−27×3+90=0$$

Therefore, one of the factors is $(\lambda - 3)$.

$$\lambda^3−4\lambda^2−27\lambda+90=(\lambda−3)(\lambda^2−\lambda−30)$$

$$(\lambda−3)(\lambda^2-\lambda−30)=(\lambda−3)(\lambda+5)(\lambda−6)$$

Based on the calculation above, the eigenvalues are 3, -5, and 6.

<br></br>
**Step 4: Finding the eigenvector corresponding to eigenvalue 3.**

$$\begin{pmatrix} -5 & -4 & 2 \\ -2 & -2 & 2 \\ 4 & 2 & 2 \end{pmatrix}
\begin{pmatrix} X \\ Y \\ Z \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 0 \end{pmatrix}$$

Setting the X to 1 results in, as the first two equations:

$$−5−4Y+2Z=0$$
$$−2−2Y+2Z=0$$

which, if performed upon using elimination, merits:

$$3+2Y=0$$

and thus,

$$Y = \frac{−2}{3}$$

Substituting Y back into the second equation, it can be inferred that,

$$Z = -\frac{1}{2}$$

All these variables work for all equations in question.

Hence, the eigenvector is:

$$(1, -\frac{3}{2}, -\frac{1}{2})$$

For convenience, we can scale up by a factor of 2, to get:

$$(2, -3, -1)$$

<br></br>
**Step 5: Finding the eigenvector corresponding to eigenvalue -5.**

$$\begin{pmatrix} 3 & -4 & 2 \\ -2 & 6 & 2 \\ 4 & 2 & 10 \end{pmatrix}
\begin{pmatrix} X \\ Y \\ Z \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 0 \end{pmatrix}$$

Setting the X to 1 results in, as the first two equations:

$$−3−4Y+2Z=0$$
$$−2−6Y+2Z=0$$

which, if performed upon using elimination, merits:

$$-5+10Y=0$$

and thus,

$$Y = \frac{1}{2}$$

Substituting Y back into the second equation, it can be inferred that,

$$Z = -\frac{1}{2}$$

All these variables work for all equations in question.

Hence, the eigenvector is:

$$(1, -\frac{1}{2}, \frac{1}{2})$$

For convenience, we can scale up by a factor of 2, to get:

$$(2, -1, 1)$$

<br></br>
**Step 6: Finding the eigenvector corresponding to eigenvalue 6.**

$$\begin{pmatrix} -8 & -4 & 2 \\ -2 & -5 & 2 \\ 4 & 2 & -1 \end{pmatrix}
\begin{pmatrix} X \\ Y \\ Z \end{pmatrix} = \begin{pmatrix} 0 \\ 0 \\ 0 \end{pmatrix}$$

Setting the X to 1 results in, as the first two equations:

$$−8−4Y+2Z=0$$
$$−2−5Y+2Z=0$$

which, if performed upon using elimination, merits:

$$6-Y=0$$

and thus,

$$Y = 6$$

Substituting Y back into the second equation, it can be inferred that,

$$Z = 16$$

All these variables work for all equations in question.

Hence, the eigenvector is:

$$(1, 6, 16)$$

<br></br>
*In summary, it can be concluded that:*

The matrix A has three distinct eigenvalues: 3, -5, and 6.<br></br>
The eigenvector corresponding to eigenvalue 3 is (2, -3, -1).<br></br>
The eigenvector corresponding to eigenvalue -5 is (2, 1, -1).<br></br>
The eigenvector corresponding to eigenvalue 6 is (1, 6, 16).<br></br>

<br></br>
***Concatenating Eigenvalues and Eigenvectors to Form a Matrix (Reversal)***

All eigenvectors of the matrix A can be concatenated in a matrix with each column corresponding to each eigenvector.

Let V be the name of the matrix.

$$V = \begin{bmatrix} 2 & 2 & 1 \\ -3 & 1 & 6 \\ -1 & -1 & 16 \end{bmatrix}$$

Let E be the name of the matrix for a column of eigenvalues.

$$E = \begin{bmatrix} 3 \\ -5 \\ 6 \end{bmatrix}$$

Then, the eigendecomposition is given by:

$$A = V \cdot diag(E) \cdot V^{-1}$$

> diag(E) is a diagonal matrix containing all the eigenvalues.

$$diag(E)= \begin{bmatrix} 3 & 0 & 0 \\ 0 & -5 & 0 \\ 0 & 0 & 6 \end{bmatrix}$$

In summary, the combined equation in the decomposition process would be:

$$\begin{bmatrix} 2 & -4 & 2 \\ -2 & 1 & 2 \\ 4 & 2 & 5 \end{bmatrix} = \begin{bmatrix} 2 & 2 & 1 \\ -3 & 1 & 6 \\ -1 & -1 & 16 \end{bmatrix} \begin{bmatrix} 3 & 0 & 0 \\ 0 & -5 & 0 \\ 0 & 0 & 6 \end{bmatrix} \begin{bmatrix} \frac{1}{6} & -\frac{1}{4} & \frac{1}{12} \\ \frac{159}{500} & \frac{1}{4} & \frac{57}{500} \\ \frac{303}{10000} & 0 & \frac{303}{5000} \end{bmatrix}$$

In [6]:
import numpy as np

""" In order to implement Eigendecomposition in Python,
it is recommended to import numpy library for convenience. """

def performEigenDecomposition(matrix):
    """ Returns: None
        Parameters: A matrix (numpy array)
        
        Description:
            performEigenDecomposition takes a matrix as an input parameter and
            prints the results of its Eigendecomposition on the console."""
            
    # The matrix must be a square.      
    if (matrix.shape[0] != matrix.shape[1]):
        print("ERROR: The matrix must be a square.")
        
    else:
        # Getting and splitting the eigenvalues and eigenvectors of the given matrix.
        # Since the eigenvectors resulted from the function np.linalg.eig are already
        # arranged vertically in the form of columns, transposing them is unnecessary.
        matrix_eigens = np.linalg.eig(matrix)
        matrix_eigenvals = matrix_eigens[0]
        matrix_eigenvecs = matrix_eigens[1]
        
        # The eigenvalues must be distinct (not repeated).
        if (len(matrix_eigenvals) > len(set(matrix_eigenvals))):
            print("ERROR: The matrix's eigenvalues are not distinct.")
            
        else:
            # Arrange the matrix's eigenvalues in the shape of a diagonal matrix.
            matrix_eigenvals_diag = np.diag(matrix_eigenvals)
            
            # Calculate the inversion of the matrix matrix_eigenvecs.
            matrix_eigenvecs_inverted = np.linalg.inv(matrix_eigenvecs)
            
            # Place every matrix according to the eigendecomposition structure and
            # calculate the result.
            result = matrix_eigenvecs.dot(matrix_eigenvals_diag).dot(matrix_eigenvecs_inverted)
            
            # Print accurate results on the console.
            print("Performing EigenDecomposition on matrix:\n", matrix, "\n")
            
            for i in range(len(matrix_eigenvals)):
                print(f"The matrix's eigenvector {np.transpose(matrix_eigenvecs)[i]}",\
                      f"corresponds to the eigenvalue {round(matrix_eigenvals[i])}.\n")
            
            print("(Reversal) Concatenating eigenvectors and eigenvalues:\n", result)

""" DRIVER """

# A = np.array([[-2, -4,  2],
#               [-2,  1,  2],  <--- example
#               [ 4,  2,  5]]) 

def getInputMatrix():
    print("Please input a matrix from a valid equation")
    print("Input Matrix")
    while True:
        row = int(input("Enter number of matrix rank [2-5] (like 3x3 or 4x4, etc): "))
        if(row < 2 or row > 5):
            continue
        else:
            while True:
                print("Enter the elements in a single line (separated by space)")
                print("For Example 3 -2 5 0 4 5 8 1 1 1 2 1 2 7 6 5 becomes \n[3,-2,5,0]\n[4,5,8,1]\n[1,1,2,1]\n[2,7,6,5]")
                elements = list(map(int, input().split()))
                if(row ** 2 != len(elements)):                  
                    print("Please enter the valid amount of elements")
                    continue
                else:
                    matrix = np.array(elements, float).reshape(row, row)
                    return matrix
                    break
            break

inputMatrix = getInputMatrix()

performEigenDecomposition(inputMatrix)

Please input a matrix from a valid equation
Input Matrix
Enter number of matrix rank [2-5] (like 3x3 or 4x4, etc): 3
Enter the elements in a single line (separated by space)
For Example 3 -2 5 0 4 5 8 1 1 1 2 1 2 7 6 5 becomes 
[3,-2,5,0]
[4,5,8,1]
[1,1,2,1]
[2,7,6,5]
-2 -4 2 -2 1 2 4 2 5
Performing EigenDecomposition on matrix:
 [[-2. -4.  2.]
 [-2.  1.  2.]
 [ 4.  2.  5.]] 

The matrix's eigenvector [ 0.81649658  0.40824829 -0.40824829] corresponds to the eigenvalue -5.0.

The matrix's eigenvector [ 0.53452248 -0.80178373 -0.26726124] corresponds to the eigenvalue 3.0.

The matrix's eigenvector [0.05842062 0.35052374 0.93472998] corresponds to the eigenvalue 6.0.

(Reversal) Concatenating eigenvectors and eigenvalues:
 [[-2. -4.  2.]
 [-2.  1.  2.]
 [ 4.  2.  5.]]
